# Generated by Django 4.2.4 on 2023-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('name', models.TextField()),
                ('quantity', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
